from typing import Protocol
from uuid import UUID

from app.domain.entities.memory import Memory


class MemoryRepository(Protocol):
    async def add(self, memory: Memory) -> Memory: ...

    async def get(self, memory_id: UUID) -> Memory | None: ...

    async def update(self, memory: Memory) -> Memory: ...

    async def delete(self, memory_id: UUID) -> bool: ...

    async def list_for_user(self, user_id: str, limit: int = 100) -> list[Memory]: ...
